numbers = [3,5,10,18,20,50]
#print(type(numbers))
numbers.append(40)#This function is also add a new elements in last index
print(numbers)
numbers.insert(1,3)#This function is also add a new elements in user input index 
print(numbers)
numbers.remove(3)#This function is also remove a elements on the list 
print(numbers)
numbers.pop()#This function is also remove a element in last indexA
print(numbers)
numbers.sort()#This function is also change the original list 
print(numbers)
numbers.reverse()#This function is also change the original list 
print(numbers)
